/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import basededatos.Conexion;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author David
 */
public class EliminarReserva extends javax.swing.JFrame {
  PreparedStatement ps = null;
DefaultTableModel modelo ;
    public EliminarReserva() {
        
        initComponents();
     llenarTabla () ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        botoneliminarReserva = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Telefono", "Dirección", "Correo ", "Nº habitación", "Tipo Habitación", "Tipo Camas", "Vip", "Garaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        botoneliminarReserva.setText("Eliminar Reserva");
        botoneliminarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botoneliminarReservaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(botoneliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(botoneliminarReserva, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botoneliminarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botoneliminarReservaActionPerformed
        int opcion = JOptionPane.showConfirmDialog(null,"¿Está seguro de que desea eliminar la reserva?","Confirmacion de eliminar",JOptionPane.YES_NO_OPTION);
        if(opcion == JOptionPane.YES_OPTION){
            Connection con = null;
            try{
            
            //conexion base de datos    
            
            con = Conexion.establecerConexionBD();
            
            int fila = tablaDatos.getSelectedRow();
            String codigo = tablaDatos.getValueAt(fila, 0).toString();
            
            ps = (PreparedStatement) con.prepareStatement("DELETE FROM reservas WHERE DNI=?");
            ps.setString(1,codigo);
            ps.execute();
            
            //tabla
            
           
            modelo.removeRow(fila);
            
            JOptionPane.showMessageDialog(null,"¡Producto Eliminado!");
          
            con.close();
            }catch(SQLException e){
                System.out.println(e);
         }
        }
    }//GEN-LAST:event_botoneliminarReservaActionPerformed

    /**
 
     */
    public static void eliminarReserva() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarReserva().setVisible(true);
            }
        });
    }

    
    public void llenarTabla(){
       /* DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Object rowDatos[] = new Object[11];
        for(int i = 0;i <reservas.size();i++){
            rowDatos[0]= reservas.get(i).getDni();
            rowDatos[1]= reservas.get(i).getNombre();
            rowDatos[2]= reservas.get(i).getTelefono();
            rowDatos[3]= reservas.get(i).getDireccion();
            rowDatos[4]= reservas.get(i).getCorreoElectronico();
            rowDatos[5]= reservas.get(i).getNumeroHabitacion();
            rowDatos[6]= reservas.get(i).getTipoHabitacion();
            rowDatos[7]= reservas.get(i).getTipoCamas();
            rowDatos[8]= reservas.get(i).getVip();
            rowDatos[9]= reservas.get(i).getGaraje();
            modelo.addRow(rowDatos);

        }  
*/
       Connection con = null;
        try{
            
            //base de datos
            con = Conexion.establecerConexionBD();
            ps = (PreparedStatement)con.prepareStatement("SELECT * FROM reservas");
            ResultSet rs = ps.executeQuery();
            
            //tabla
            
            modelo = (DefaultTableModel) tablaDatos.getModel();
           
            int cantidadColl = rs.getMetaData().getColumnCount();
            while(rs.next()){
                Object rowDatos[] = new Object[cantidadColl];
                for(int i=0;i<cantidadColl;i++){
                    rowDatos[i]= rs.getString(i+1);
                }
                modelo.addRow(rowDatos);
            }
    }catch(SQLException ex){
        System.out.println(ex);
    }
    
}
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botoneliminarReserva;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
