/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import basededatos.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author David
 */
public class ModificarReservas extends javax.swing.JFrame {

   PreparedStatement ps = null ;
   DefaultTableModel modelo  ;
    public ModificarReservas() {
        initComponents();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoVip = new javax.swing.ButtonGroup();
        grupoGaraje = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        labelDni = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelTlf = new javax.swing.JLabel();
        labelDir = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        labelNHab = new javax.swing.JLabel();
        labelTHab = new javax.swing.JLabel();
        labelTCamas = new javax.swing.JLabel();
        labelVIP = new javax.swing.JLabel();
        labelGaraje = new javax.swing.JLabel();
        textFieldDNI = new javax.swing.JTextField();
        textFieldNombre = new javax.swing.JTextField();
        textFieldTelefono = new javax.swing.JTextField();
        textFieldDireccion = new javax.swing.JTextField();
        textFieldCorreo = new javax.swing.JTextField();
        textFieldNHabitacion = new javax.swing.JTextField();
        comboBoxTHab = new javax.swing.JComboBox<>();
        comboBoxTCamas = new javax.swing.JComboBox<>();
        VipSi = new javax.swing.JRadioButton();
        GarajeSi = new javax.swing.JRadioButton();
        GarajeNone = new javax.swing.JRadioButton();
        VipNone = new javax.swing.JRadioButton();
        VipNo = new javax.swing.JRadioButton();
        GarajeNo = new javax.swing.JRadioButton();
        labelDni1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Telefono", "Direccion", "CorreoElectronico", "Num. Hab", "Tipo. Hab", "Tipo Camas", "Vip", "Garaje"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        labelDni.setText("Dni:");

        labelNombre.setText("Nombre:");

        labelTlf.setText("Teléfono:");

        labelDir.setText("Dirección:");

        labelCorreo.setText("Correo electrónico:");

        labelNHab.setText("Número de habitación:");

        labelTHab.setText("Tipo de habitación:");

        labelTCamas.setText("Tipo de camas:");

        labelVIP.setText("Vip:");

        labelGaraje.setText("Garaje:");

        comboBoxTHab.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Normal", "Suit", "Duplex" }));
        comboBoxTHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxTHabActionPerformed(evt);
            }
        });

        comboBoxTCamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Individual", "Doble", "Matrimonio", "Triple", "Cama de agua" }));

        grupoVip.add(VipSi);
        VipSi.setText("Si");

        grupoGaraje.add(GarajeSi);
        GarajeSi.setText("Si");

        grupoGaraje.add(GarajeNone);
        GarajeNone.setSelected(true);
        GarajeNone.setText("None");

        grupoVip.add(VipNone);
        VipNone.setSelected(true);
        VipNone.setText("None");

        grupoVip.add(VipNo);
        VipNo.setText("No");

        grupoGaraje.add(GarajeNo);
        GarajeNo.setText("No");

        labelDni1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelDni1.setText("MODIFICAR RESERVA");
        labelDni1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1013, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(labelDir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTlf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelNHab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTHab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelVIP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelTCamas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(labelGaraje, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(textFieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(textFieldDireccion)
                                        .addComponent(textFieldCorreo)
                                        .addComponent(textFieldNHabitacion)
                                        .addComponent(comboBoxTHab, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(GarajeNone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(GarajeSi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(VipNone, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(VipSi, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VipNo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GarajeNo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(comboBoxTCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(454, 454, 454)
                        .addComponent(labelDni1)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelDni1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(textFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelDni, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTlf, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelDir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(textFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(textFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelNHab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(textFieldNHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTHab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTHab, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboBoxTCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelVIP, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VipNone)
                            .addComponent(VipSi)
                            .addComponent(VipNo))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelGaraje, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GarajeNone)
                            .addComponent(GarajeSi)
                            .addComponent(GarajeNo))
                        .addGap(35, 35, 35)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            Connection con = null;
            try{
            
            //Base de Datos    
            
            con = Conexion.establecerConexionBD();
            ps = (PreparedStatement) con.prepareStatement("UPDATE reservas SET dni=?,nombre=?,telefono=? direccion=?,correoElectronico=?,numeroHabitacion=?,tipoHabitacion=?,tipoCamas=?, vip=?,garaje=? WHERE dni=?");
            ps.setString(1,textFieldDNI.getText());
            ps.setString(2, textFieldNombre.getText());
            ps.setInt(3, Integer.valueOf(textFieldTelefono.getText()) );
          ps.setString(4,textFieldDireccion.getText());
          ps.setString(5,textFieldCorreo.getText());
          ps.setInt(6,Integer.valueOf(textFieldNHabitacion.getText()) );
          ps.setString(7,comboBoxTHab.getSelectedItem().toString());
        ps.setString(8,comboBoxTCamas.getSelectedItem().toString());
         
        if(VipNone.isSelected()){
             ps.setString(9,VipNone.getLabel());
        }else if(VipSi.isSelected()){
             ps.setString(  9,VipSi.getLabel());
        }else if(VipNo.isSelected()){
            ps.setString(9,VipNo.getLabel()); 
        }
      
        if(GarajeNone.isSelected()){
            ps.setString(10,GarajeNone.getLabel());
        }else if(GarajeSi.isSelected()){
            ps.setString(10,GarajeSi.getLabel());
        }else if(GarajeNo.isSelected()){
           ps.setString(10,GarajeNo.getLabel());
        
         
         
         }
          ps.setString(11,textFieldDNI.getText());
            ps.executeUpdate();
            
            //tabla
            
            int fila = tablaDatos.getSelectedRow();
            tablaDatos.setValueAt(textFieldDNI.getText(), fila, 0);
            tablaDatos.setValueAt(textFieldNombre.getText(), fila, 1);
            tablaDatos.setValueAt(textFieldTelefono.getText(), fila, 2);
            tablaDatos.setValueAt(textFieldDireccion.getText(), fila, 3);
            tablaDatos.setValueAt(textFieldCorreo.getText(), fila, 4);
            tablaDatos.setValueAt(textFieldNHabitacion.getText(), fila, 5);
            tablaDatos.setValueAt(comboBoxTHab.getSelectedItem().toString(), fila, 6);
            tablaDatos.setValueAt(comboBoxTCamas.getSelectedItem().toString(), fila, 7);
                if(VipNone.isSelected()){
             tablaDatos.setValueAt(VipNone.getLabel(), fila, 8);
        }else if(VipSi.isSelected()){
            tablaDatos.setValueAt(VipSi.getLabel(), fila, 8);
        }else if(VipNo.isSelected()){
            tablaDatos.setValueAt(VipNo.getLabel(), fila, 8); 
        }
      
        if(GarajeNone.isSelected()){
            tablaDatos.setValueAt(GarajeNone.getLabel(), fila, 9);
        }else if(GarajeSi.isSelected()){
            tablaDatos.setValueAt(GarajeSi.getLabel(), fila, 9);
        }else if(GarajeNo.isSelected()){
           tablaDatos.setValueAt(GarajeNo.getLabel(), fila, 9);
            
        }    
            JOptionPane.showMessageDialog(null,"¡Reserva Modificada!");
           
            
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Hubo un error al modificar la reserva, intentelo de nuevo");
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMouseClicked
          
        Connection con = null;
        try{
            con = Conexion.establecerConexionBD();
            int fila = tablaDatos.getSelectedRow();
            String codigo = tablaDatos.getValueAt(fila, 0).toString();
            ps = (PreparedStatement) con.prepareStatement("SELECT dni,nombre,telefono,direccion,correoElectronico,numeroHabitacion,tipoHabitacion,tipoCamas, vip,garaje FROM reservas  WHERE dni=?");
            ps.setString(1, codigo);
           ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
           textFieldDNI.setText(rs.getString("dni"));
         textFieldNombre.setText(rs.getString("nombre"));
           textFieldTelefono.setText(rs.getString("telefono"));
       textFieldDireccion.setText(rs.getString("direccion"));
         textFieldCorreo.setText(rs.getString("correoElectronico"));
         textFieldNHabitacion.setText(rs.getString("numeroHabitacion"));
         if(rs.getString("tipoHabitacion")=="Normal") {
         comboBoxTHab.setSelectedIndex(1);
         
         
         } else if (rs.getString("tipoHabitacion")=="Suit"){
         
             comboBoxTHab.setSelectedIndex(2);
         
         
         } else if (rs.getString("tipoHabitacion")=="Dúplex"){
         
             comboBoxTHab.setSelectedIndex(3);
         
         
         } 
         
          if(rs.getString("tipoCamas")=="Individual") {
         comboBoxTCamas.setSelectedIndex(1);
         
         
         } else if (rs.getString("tipoCamas")=="Doble"){
         
             comboBoxTCamas.setSelectedIndex(2);
         
         
         }  else if (rs.getString("tipoCamas")=="Matrimonio"){
         
             comboBoxTCamas.setSelectedIndex(3);
         
         } else if (rs.getString("tipoCamas")=="Triple"){
         
             comboBoxTCamas.setSelectedIndex(4);
         
         }
          else if (rs.getString("tipoCamas")=="Cama de agua"){
         
             comboBoxTCamas.setSelectedIndex(5);
         
         }
         
         
         
    
      if(rs.getString("vip")=="None") {
         VipNone.setSelected(true);
         
         
         } else if (rs.getString("vip")=="true"){
         
             VipSi.setSelected(true);
         
         
         }
         else if (rs.getString("vip")=="false"){
         
              VipNo.setSelected(true);
         
         
         }
      
      
        if(rs.getString("garaje")=="None") {
         GarajeNone.setSelected(true);
         
         
         } else if (rs.getString("garaje")=="true"){
         
             GarajeSi.setSelected(true);
         
         
         }
         else if (rs.getString("garaje")=="false"){
         
              GarajeNo.setSelected(true);
         
         
         }
      
            }
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_tablaDatosMouseClicked

    private void comboBoxTHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxTHabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxTHabActionPerformed

    
     public void llenarTabla(){
       /* DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        Object rowDatos[] = new Object[11];
        for(int i = 0;i <reservas.size();i++){
            rowDatos[0]= reservas.get(i).getDni();
            rowDatos[1]= reservas.get(i).getNombre();
            rowDatos[2]= reservas.get(i).getTelefono();
            rowDatos[3]= reservas.get(i).getDireccion();
            rowDatos[4]= reservas.get(i).getCorreoElectronico();
            rowDatos[5]= reservas.get(i).getNumeroHabitacion();
            rowDatos[6]= reservas.get(i).getTipoHabitacion();
            rowDatos[7]= reservas.get(i).getTipoCamas();
            rowDatos[8]= reservas.get(i).getVip();
            rowDatos[9]= reservas.get(i).getGaraje();
            modelo.addRow(rowDatos);

        }  
*/
       Connection con = null;
        try{
            
            //base de datos
            con = Conexion.establecerConexionBD();
            ps = (PreparedStatement)con.prepareStatement("SELECT * FROM reservas");
            ResultSet rs = ps.executeQuery();
            
            //tabla
            
            modelo = (DefaultTableModel) tablaDatos.getModel();
           
            int cantidadColl = rs.getMetaData().getColumnCount();
            while(rs.next()){
                Object rowDatos[] = new Object[cantidadColl];
                for(int i=0;i<cantidadColl;i++){
                    rowDatos[i]= rs.getString(i+1);
                }
                modelo.addRow(rowDatos);
            }
    }catch(SQLException ex){
        System.out.println(ex);
    }
    
}
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void modificarReservas() {
  
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton GarajeNo;
    private javax.swing.JRadioButton GarajeNone;
    private javax.swing.JRadioButton GarajeSi;
    private javax.swing.JRadioButton VipNo;
    private javax.swing.JRadioButton VipNone;
    private javax.swing.JRadioButton VipSi;
    private javax.swing.JComboBox<String> comboBoxTCamas;
    private javax.swing.JComboBox<String> comboBoxTHab;
    private javax.swing.ButtonGroup grupoGaraje;
    private javax.swing.ButtonGroup grupoVip;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelDir;
    private javax.swing.JLabel labelDni;
    private javax.swing.JLabel labelDni1;
    private javax.swing.JLabel labelGaraje;
    private javax.swing.JLabel labelNHab;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTCamas;
    private javax.swing.JLabel labelTHab;
    private javax.swing.JLabel labelTlf;
    private javax.swing.JLabel labelVIP;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField textFieldCorreo;
    private javax.swing.JTextField textFieldDNI;
    private javax.swing.JTextField textFieldDireccion;
    private javax.swing.JTextField textFieldNHabitacion;
    private javax.swing.JTextField textFieldNombre;
    private javax.swing.JTextField textFieldTelefono;
    // End of variables declaration//GEN-END:variables
}
